# -*- encoding: utf-8 -*-
"""
KERI
keri.app.keeping module

Native LMDB key storage and shared key-management exports.
"""

from hio.base import doing

from ..core import Prefixer, Number, Cipher
from ..db import (openLMDB, LMDBer, Suber, CryptSignerSuber, CesrSuber,
                  CatCesrIoSetSuber, Komer)
from .basekeeping import (Algoage as Algoage, Algos as Algos,
                          PubLot as PubLot, PreSit as PreSit,
                          PrePrm as PrePrm, PubSet as PubSet, riKey as riKey,
                          Creator as Creator, RandyCreator as RandyCreator,
                          SaltyCreator as SaltyCreator, Creatory as Creatory,
                          Initage as Initage, Manager as Manager,
                          ManagerDoer as ManagerDoer)


def openKS(name="test", **kwa):
    """
    Returns contextmanager generated by openLMDB but with Keeper instance as
    KeyStore
    default name="test"
    default temp=True,

    openLMDB Parameters:
        cls is Class instance of subclass instance
        name is str name of LMDBer dirPath so can have multiple databasers
        at different directory path names thar each use different name

        temp is Boolean, True means open in temporary directory, clear on close
        Otherwise open in persistent directory, do not clear on close
    """
    return openLMDB(cls=Keeper, name=name, **kwa)


class Keeper(LMDBer):
    """
    Keeper sets up named sub databases for key pair storage (KS).
    Methods provide key pair creation, storage, and data signing.

    Attributes:  (inherited)
        name (str): unique path component used in directory or file path name
        base (str): another unique path component inserted before name
        temp (bool): True means use /tmp directory
        headDirPath is head directory path
        path is full directory path
        perm is numeric os permissions for directory and/or file(s)
        filed (bool): True means .path ends in file. Otherwise .path ends in directory.

        mode (str): file open mode if filed
        fext (str): file extension
        file (File)
        opened is Boolean, True means directory created and if file then file is opened. False otherwise.

        env (lmdb.env): LMDB main (super) database environment
        readonly (bool): True means open LMDB env as readonly

    Attributes:
        gbls (Suber): named sub DB whose values are global parameters
            for all prefixes
            Key is parameter labels
            Value is parameter::

                parameters:
                    aeid (bytes): fully qualified qb64 non-transferable identifier
                        prefix for authentication via signing and asymmetric encryption
                        of secrets using the associated (public, private) key pair.
                        Secrets include both salts and private keys for all key sets
                        in keeper. Defaults to empty which means no authentication
                        or encryption of key sets.

                    pidx (bytes): hex index of next prefix key-pair sequence to be incepted
                    algo (str): default root algorithm for generating key pair
                    salt (bytes): root salt for generating key pairs
                    tier (bytes): default root security tier for root salt

        pris (CryptSignerSuber): named sub DB whose keys are public key
            from key pair and values are private keys from key pair
            Key is public key (fully qualified qb64)
            Value is private key (fully qualified qb64)

        pres (CesrSuber): named sub DB whose values are prefixes or first
            public keys
            Key is first public key in key sequence for a prefix (fully qualified qb64)
            Value is prefix or first public key (temporary) (fully qualified qb64

        prms (Komer): named sub DB whose values are serialized dicts of
            PrePrm instance
            Key is identifier prefix (fully qualified qb64)
            Value is serialized parameter dict of public key parameters::

                {
                    pidx: ,
                    algo: ,
                    salt: ,
                    stem: ,
                    tier: ,
                }

        sits (Komer): named sub DB whose values are serialized dicts of
            PreSit instance
            Key is identifier prefix (fully qualified qb64)
            Value is serialized parameter dict of public key situation::

                {
                  old: { pubs: ridx, kidx,  dt },
                  new: { pubs: ridx, kidx, dt },
                  nxt: { pubs: ridx, kidx, dt }
                }

        pubs (Komer): named sub DB whose values are serialized lists of
            public keys
            Enables lookup of public keys from prefix and ridx for replay of
            public keys by prefix in establishment event order.
            Key is prefix.ridx (rotation index as 32 char hex string)
            use riKey(pre, ri)

            Value is serialized list of fully qualified public keys that are the
            current signing keys after the rotation given by rotation index

    Properties:


    """
    TailDirPath = "keri/ks"
    AltTailDirPath = ".keri/ks"
    TempPrefix = "keri_ks_"
    MaxNamedDBs = 10

    def __init__(self, headDirPath=None, perm=None, reopen=False, **kwa):
        """
        Setup named sub databases.

        Inherited Parameters:
            name is str directory path name differentiator for main database.
            When system employs more than one keri database, name allows
            differentiating each instance by name. Default name='main'.
            temp is boolean, assign to .temp.
            True then open in temporary directory, clear on close.
            Otherwise then open persistent directory, do not clear on close.
            Default temp=False.
            headDirPath is optional str head directory pathname for main database.
            If not provided use default .HeadDirpath. Default headDirPath=None.
            perm is numeric optional os dir permissions mode. Default perm=None.
            reopen is boolean, IF True then database will be reopened by this init.
            Default reopen=True.

        Notes:

        dupsort=True for sub DB means allow unique (key,pair) duplicates at a key.
        Duplicate means that is more than one value at a key but not a redundant
        copies a (key,value) pair per key. In other words the pair (key,value)
        must be unique both key and value in combination.
        Attempting to put the same (key,value) pair a second time does
        not add another copy.

        Duplicates are inserted in lexocographic order by value, insertion order.

        """
        if perm is None:
            perm = self.Perm  # defaults to restricted permissions for non temp

        super(Keeper, self).__init__(headDirPath=headDirPath, perm=perm,
                                     reopen=reopen, **kwa)

    def reopen(self, **kwa):
        """
        Open sub databases
        """
        super(Keeper, self).reopen(**kwa)

        # Create by opening first time named sub DBs within main DB instance
        # Names end with "." as sub DB name must include a non Base64 character
        # to avoid namespace collisions with Base64 identifier prefixes.

        self.gbls = Suber(db=self, subkey='gbls.')
        self.pris = CryptSignerSuber(db=self, subkey='pris.')
        self.prxs = CesrSuber(db=self,
                             subkey='prxs.',
                             klas=Cipher)
        self.nxts = CesrSuber(db=self,
                             subkey='nxts.',
                             klas=Cipher)
        self.smids = CatCesrIoSetSuber(db=self,
                                      subkey='smids.',
                                      klas=(Prefixer, Number))
        self.rmids = CatCesrIoSetSuber(db=self,
                                      subkey='rmids.',
                                      klas=(Prefixer, Number))
        self.pres = CesrSuber(db=self,
                             subkey='pres.',
                             klas=Prefixer)
        self.prms = Komer(db=self,
                          subkey='prms.',
                          klas=PrePrm)  # New Prefix Parameters
        self.sits = Komer(db=self,
                          subkey='sits.',
                          klas=PreSit)  # Prefix Situation
        self.pubs = Komer(db=self,
                          subkey='pubs.',
                          klas=PubSet)  # public key set at pre.ridx
        return self.opened


class KeeperDoer(doing.Doer):
    """
    Basic Keeper Doer ( LMDB Database )

    Attributes:
        keeper (Keeper): native key store
    """

    def __init__(self, keeper, **kwa):
        """
        Parameters:
            keeper (Keeper): native key store
        """
        super(KeeperDoer, self).__init__(**kwa)
        self.keeper = keeper

    def enter(self, *, temp=None):
        """"""
        if not self.keeper.opened:
            self.keeper.reopen()  # reopen(temp=temp)

    def exit(self):
        """"""
        self.keeper.close(clear=self.keeper.temp)
